"""
ERA5 Climate Dashboard — Cinematic Intro + Dark Redesign
=========================================================
Paste the INDEX_STRING into your app.index_string assignment.
Copy ERA5_styles.css into your assets/ folder.

Usage in dashboard.py:
    app.index_string = INDEX_STRING
"""

# ─────────────────────────────────────────────────────────────
# 1.  INDEX_STRING  (drop-in for app.index_string)
# ─────────────────────────────────────────────────────────────
INDEX_STRING = '''<!DOCTYPE html>
<html lang="fr" data-theme="dark">
<head>
  {%metas%}
  <title>Climat Méditerranée · ERA5</title>
  {%favicon%}
  {%css%}
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet"/>
  <style>
    /* ── Inline critical styles (keep CSS file for the rest) ── */
    html,body{background:#080c18!important;color:rgba(226,232,255,.95)!important;
      font-family:"DM Sans",system-ui,sans-serif!important;}
  </style>
</head>
<body>

<!-- ══════════════════════════════════════
     CINEMATIC INTRO
══════════════════════════════════════ -->
<div id="split-left"  class="split-panel"></div>
<div id="split-right" class="split-panel"></div>

<div id="intro-overlay">
  <!-- Star field (generated by JS below) -->
  <div id="intro-stars"></div>

  <!-- Globe -->
  <div class="intro-globe-container">
    <svg id="intro-globe" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <radialGradient id="gG" cx="40%" cy="35%" r="65%">
          <stop offset="0%"   stop-color="#1e3a6b" stop-opacity="0.9"/>
          <stop offset="60%"  stop-color="#0d1f45" stop-opacity="0.95"/>
          <stop offset="100%" stop-color="#06102a" stop-opacity="1"/>
        </radialGradient>
        <radialGradient id="gS" cx="35%" cy="30%" r="50%">
          <stop offset="0%"   stop-color="#6366f1" stop-opacity="0.25"/>
          <stop offset="100%" stop-color="#6366f1" stop-opacity="0"/>
        </radialGradient>
        <clipPath id="gC"><circle cx="100" cy="100" r="88"/></clipPath>
      </defs>
      <circle cx="100" cy="100" r="88" fill="url(#gG)" stroke="#6366f1" stroke-width="0.8" stroke-opacity="0.6"/>
      <circle cx="100" cy="100" r="88" fill="url(#gS)"/>
      <!-- Lat lines -->
      <ellipse cx="100" cy="40"  rx="0"  ry="0"  stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.35" fill="none" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="67"  rx="65" ry="13" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.35" fill="none" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="100" rx="88" ry="17" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.35" fill="none" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="133" rx="65" ry="13" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.35" fill="none" clip-path="url(#gC)"/>
      <!-- Lon lines -->
      <ellipse cx="100" cy="100" rx="88" ry="88" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.3" fill="none" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="100" rx="44" ry="88" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.3" fill="none" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="100" rx="0"  ry="88" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.3" fill="none" transform="rotate(60 100 100)" clip-path="url(#gC)"/>
      <ellipse cx="100" cy="100" rx="44" ry="88" stroke="#6366f1" stroke-width="0.4" stroke-opacity="0.3" fill="none" transform="rotate(90 100 100)" clip-path="url(#gC)"/>
      <!-- Landmasses -->
      <g clip-path="url(#gC)" opacity="0.7">
        <path d="M72 52 L78 48 L88 46 L96 50 L100 56 L95 62 L88 64 L80 60 Z"
              fill="#22d3ee" fill-opacity="0.25" stroke="#22d3ee" stroke-width="0.5"/>
        <path d="M68 90 L120 88 L128 96 L120 104 L68 106 L60 98 Z"
              fill="#fbbf24" fill-opacity="0.2" stroke="#fbbf24" stroke-width="0.5"/>
        <path d="M72 74 L125 72 L128 82 L68 85 Z"
              fill="#6366f1" fill-opacity="0.3"/>
        <rect x="95" y="90" width="6" height="10" rx="1" fill="#f97316" fill-opacity="0.5"/>
      </g>
      <circle cx="100" cy="100" r="88" fill="none" stroke="#22d3ee" stroke-width="1" stroke-opacity="0.2"/>
      <circle cx="100" cy="100" r="92" fill="none" stroke="#6366f1" stroke-width="0.5" stroke-opacity="0.15"/>
      <ellipse cx="74" cy="68" rx="18" ry="12" fill="white" fill-opacity="0.04" transform="rotate(-25 74 68)"/>
    </svg>
  </div>

  <div class="intro-glow-ring"></div>

  <!-- Center content -->
  <div id="intro-content">
    <div class="intro-badge">
      <span class="intro-badge-dot"></span>
      Live data · ERA5 Copernicus
    </div>

    <h1 id="intro-title"><span class="intro-cursor"></span></h1>
    <div id="intro-subtitle">Tunisie · Europe · 1980 — 2024</div>

    <svg id="intro-wave" viewBox="0 0 400 36" fill="none">
      <defs>
        <linearGradient id="wG" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0%"   stop-color="#6366f1" stop-opacity="0"/>
          <stop offset="30%"  stop-color="#6366f1"/>
          <stop offset="70%"  stop-color="#22d3ee"/>
          <stop offset="100%" stop-color="#22d3ee" stop-opacity="0"/>
        </linearGradient>
      </defs>
      <path class="wave-path"
        d="M0 18 Q50 6 100 18 Q150 30 200 18 Q250 6 300 18 Q350 30 400 18"
        stroke="url(#wG)" stroke-width="1.5" fill="none"/>
      <path
        d="M0 18 Q50 6 100 18 Q150 30 200 18 Q250 6 300 18 Q350 30 400 18"
        stroke="url(#wG)" stroke-width="4" fill="none" opacity="0.15"/>
    </svg>

    <div id="intro-progress-wrap">
      <div class="intro-progress-label">
        <span id="intro-progress-text">Initialisation...</span>
        <span id="intro-progress-pct">0%</span>
      </div>
      <div class="intro-progress-track">
        <div id="intro-progress-fill"></div>
      </div>
    </div>
  </div>

  <div id="intro-skip">Appuyer sur une touche pour passer</div>
</div>
<!-- /intro -->

<!-- ══════════════════════════════════════
     MAIN DASHBOARD HEADER
══════════════════════════════════════ -->
<div id="app-container">
  <header id="main-header">
    <div class="header-left">
      <div class="live-badge">
        <span class="live-dot"></span>
        Live data · ERA5 Copernicus
      </div>
      <div class="header-title">Climat Méditerranée</div>
      <div class="header-subtitle">Tunisie · Europe · 1980 — 2024</div>
    </div>
    <div class="header-meta">
      <div class="meta-item"><span class="meta-label">Source</span><span class="meta-value">Copernicus CDS</span></div>
      <div class="meta-item"><span class="meta-label">Résolution</span><span class="meta-value">0.25° × 0.25°</span></div>
      <div class="meta-item"><span class="meta-label">Zones</span><span class="meta-value">3 régions</span></div>
      <div class="meta-item"><span class="meta-label">Période</span><span class="meta-value">45 années</span></div>
      <div class="meta-item"><span class="meta-label">Tests</span><span class="meta-value">Mann-Kendall + Sen</span></div>
    </div>
  </header>

  <!-- Dash app mounts here -->
  {%app_entry%}

  <footer id="main-footer">
    <div>
      <div class="footer-group-label">Données</div>
      <a class="footer-link" href="https://cds.climate.copernicus.eu" target="_blank">Copernicus Climate Data Store</a>
      <div class="footer-text">ERA5 single-levels reanalysis</div>
    </div>
    <div>
      <div class="footer-group-label">Méthodes statistiques</div>
      <div class="footer-text" style="font-family:DM Mono,monospace;font-size:12px;">Mann-Kendall (τ, p)</div>
      <div class="footer-text">Sen\'s slope · OLS · Anomalies WMO</div>
    </div>
    <div>
      <div class="footer-group-label">Projet</div>
      <div class="footer-text" style="font-weight:600;">ESSAI 2026</div>
      <div class="footer-text">Bacem Ben Ahmad — Mme Tej</div>
    </div>
  </footer>
</div>

{%config%}
{%scripts%}
{%renderer%}

<!-- ══════════════════════════════════════
     INTRO ANIMATION SCRIPT
══════════════════════════════════════ -->
<script>
(function() {
  "use strict";

  var TITLE   = "Climat Méditerranée";
  var LABELS  = [
    [0,   "Chargement ERA5..."],
    [20,  "Lecture des données 1980 → 1990..."],
    [40,  "Traitement des anomalies thermiques..."],
    [65,  "Calcul Mann-Kendall + Sen slope..."],
    [85,  "Génération des cartes méditerranéennes..."],
    [100, "Prêt — 1980 → 2024"]
  ];

  /* ── Stars ── */
  var starsEl = document.getElementById("intro-stars");
  for (var i = 0; i < 120; i++) {
    var s = document.createElement("div");
    s.className = "intro-star";
    var sz = Math.random() * 1.5 + 0.3;
    s.style.cssText =
      "left:" + (Math.random()*100) + "%;" +
      "top:"  + (Math.random()*100) + "%;" +
      "width:" + sz + "px;" +
      "height:" + sz + "px;" +
      "--dur:" + (2+Math.random()*4) + "s;" +
      "--delay:" + (Math.random()*3) + "s;" +
      "--base-opacity:" + (0.1+Math.random()*0.5) + ";";
    starsEl.appendChild(s);
  }

  /* ── Dismiss ── */
  function dismiss() {
    var ol = document.getElementById("intro-overlay");
    var sl = document.getElementById("split-left");
    var sr = document.getElementById("split-right");
    if (ol) { ol.classList.add("hidden"); setTimeout(function(){ol.remove();},500); }
    if (sl) { sl.classList.add("open"); setTimeout(function(){sl.remove();},1000); }
    if (sr) { sr.classList.add("open"); setTimeout(function(){sr.remove();},1000); }
  }
  window.addEventListener("keydown", dismiss, {once: true});

  /* ── Typewriter ── */
  var titleEl = document.getElementById("intro-title");
  var idx = 0;
  function typeChar() {
    if (idx < TITLE.length) {
      titleEl.textContent = TITLE.slice(0, ++idx);
      var cursor = document.createElement("span");
      cursor.className = "intro-cursor";
      titleEl.appendChild(cursor);
      setTimeout(typeChar, 55);
    } else {
      onTypingDone();
    }
  }
  setTimeout(typeChar, 800);

  /* ── After typing ── */
  function onTypingDone() {
    var sub  = document.getElementById("intro-subtitle");
    var wave = document.getElementById("intro-wave");
    var prog = document.getElementById("intro-progress-wrap");
    if (sub)  { setTimeout(function(){ sub.classList.add("visible"); }, 100); }
    if (wave) { setTimeout(function(){ wave.classList.add("visible"); }, 250); }
    if (prog) { setTimeout(function(){ prog.classList.add("visible"); startProgress(); }, 450); }
  }

  /* ── Progress ── */
  function startProgress() {
    var fill    = document.getElementById("intro-progress-fill");
    var textEl  = document.getElementById("intro-progress-text");
    var pctEl   = document.getElementById("intro-progress-pct");
    var cur = 0;
    var iv = setInterval(function() {
      cur = Math.min(cur + 1.8, 100);
      if (fill) fill.style.width = cur + "%";
      if (pctEl) pctEl.textContent = Math.round(cur) + "%";
      for (var j = LABELS.length - 1; j >= 0; j--) {
        if (cur >= LABELS[j][0]) {
          if (textEl) textEl.textContent = LABELS[j][1];
          break;
        }
      }
      if (cur >= 100) {
        clearInterval(iv);
        setTimeout(dismiss, 400);
      }
    }, 40);
  }
})();
</script>

</body>
</html>
'''


# ─────────────────────────────────────────────────────────────
# 2.  PLOTLY FIGURE THEME  (apply to all your go.Figure calls)
# ─────────────────────────────────────────────────────────────
PLOTLY_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(
        family="DM Sans, system-ui, sans-serif",
        color="rgba(148,163,210,0.85)",
        size=11,
    ),
    xaxis=dict(
        gridcolor="rgba(99,102,241,0.08)",
        linecolor="rgba(99,102,241,0.18)",
        tickfont=dict(family="DM Mono, monospace", size=10, color="#4a5578"),
        title_font=dict(size=11, color="rgba(100,116,165,0.8)"),
        zeroline=False,
    ),
    yaxis=dict(
        gridcolor="rgba(99,102,241,0.08)",
        linecolor="rgba(99,102,241,0.18)",
        tickfont=dict(family="DM Mono, monospace", size=10, color="#4a5578"),
        title_font=dict(size=11, color="rgba(100,116,165,0.8)"),
        zeroline=False,
    ),
    legend=dict(
        bgcolor="rgba(15,22,40,0.6)",
        bordercolor="rgba(99,102,241,0.2)",
        borderwidth=1,
        font=dict(size=11, color="rgba(148,163,210,0.85)"),
    ),
    margin=dict(l=40, r=20, t=30, b=40),
    hovermode="x unified",
    hoverlabel=dict(
        bgcolor="#0f172a",
        bordercolor="rgba(99,102,241,0.3)",
        font=dict(family="DM Mono, monospace", size=12, color="rgba(226,232,255,0.95)"),
    ),
    colorway=[
        "#6366f1",  # indigo  — primary
        "#22d3ee",  # cyan    — Europe
        "#fbbf24",  # yellow  — Tunisia
        "#a78bfa",  # violet  — Mediterranean
        "#f97316",  # orange  — heatwave / OLS
        "#22c55e",  # green
        "#ef4444",  # red
    ],
)


def apply_theme(fig):
    """Apply the ERA5 dark theme to any plotly Figure.

    Non-destructif : utilise update_xaxes/update_yaxes pour MERGE avec
    une config existante (tickmode, ticktext, range, etc.) plutot que
    de l'ecraser comme le ferait update_layout(xaxis=dict(...)).
    """
    layout = {k: v for k, v in PLOTLY_LAYOUT.items()
              if k not in ("xaxis", "yaxis")}
    fig.update_layout(**layout)
    fig.update_xaxes(**PLOTLY_LAYOUT["xaxis"])
    fig.update_yaxes(**PLOTLY_LAYOUT["yaxis"])
    return fig


# ─────────────────────────────────────────────────────────────
# 3.  DASH LAYOUT HELPERS
# ─────────────────────────────────────────────────────────────
def glass_card(children, extra_class=""):
    """Wrap content in a glassmorphism card div."""
    from dash import html
    return html.Div(
        children,
        className=f"glass-card {extra_class}".strip(),
    )


def kpi_card(label, value, subtext, icon_emoji, color_class, badge=None):
    """Build a KPI card component.

    color_class: one of 'kpi-indigo', 'kpi-cyan', 'kpi-green', 'kpi-orange'
    """
    from dash import html

    icon_map = {"kpi-indigo": "ind", "kpi-cyan": "cyn",
                "kpi-green": "grn", "kpi-orange": "org"}
    val_class = "kpi-value"
    if color_class in ("kpi-green",):
        val_class += " positive"
    if color_class == "kpi-orange":
        val_class += " warning"

    children = [
        html.Div([
            html.Div(label, className="kpi-label-text"),
            html.Div(icon_emoji, className=f"kpi-icon-box {icon_map.get(color_class,'ind')}"),
        ], className="kpi-head"),
        html.Div(value,   className=val_class),
        html.Div(subtext, className="kpi-subtext"),
    ]
    if badge:
        children.append(html.Div(f"✓ {badge}", className="kpi-sig-badge"))

    return html.Div(children, className=f"glass-card kpi-card {color_class}")


def section_label(text):
    from dash import html
    return html.Div(text, className="section-label")


def card_header(title, subtitle=None):
    from dash import html
    items = [html.Div(title, className="card-title")]
    if subtitle:
        items.append(html.Div(subtitle, className="card-subtitle"))
    return html.Div(items)


# ─────────────────────────────────────────────────────────────
# 4.  MINIMAL INTEGRATION EXAMPLE
# ─────────────────────────────────────────────────────────────
EXAMPLE = """
# ── dashboard.py (minimal example) ──────────────────────────
import dash
from dash import dcc, html
import plotly.graph_objects as go
from era5_theme import INDEX_STRING, apply_theme, glass_card, kpi_card

app = dash.Dash(__name__, assets_folder="assets")
app.index_string = INDEX_STRING

# Build a figure and apply the dark theme:
fig = go.Figure()
fig.add_scatter(x=years, y=temps, mode="lines", name="Temp. 2m",
                line=dict(color="#6366f1", width=2))
fig.add_scatter(x=years, y=ols,   mode="lines", name="OLS",
                line=dict(color="#f97316", width=1.5, dash="dash"))
fig = apply_theme(fig)

# Layout using helper classes:
app.layout = html.Div(id="app-container", children=[
    dcc.Tabs(
        className="custom-tabs",
        children=[
            dcc.Tab(label="▦  Aperçu",              className="custom-tab", selected_className="custom-tab--selected", children=[
                html.Div(className="kpi-row", children=[
                    kpi_card("Période",            "1980–2024",   "45 années", "📅", "kpi-indigo"),
                    kpi_card("Température Moyenne","24.10",       "min 5.7 · max 41.3", "🌡️", "kpi-cyan"),
                    kpi_card("Tendance OLS",        "+0.45/déc.", "Sen: +0.44/déc.", "📈", "kpi-green", "MK: très significatif"),
                    kpi_card("Épisodes ≥3J › 30°C","284",        "4 337 jours cumulés", "🔥", "kpi-orange"),
                ]),
                html.Div(className="chart-grid-2", children=[
                    glass_card([card_header("Tendance annuelle","Moyenne par année + OLS"),
                                dcc.Graph(figure=fig, config=dict(displayModeBar=False))]),
                    glass_card([card_header("Distribution saisonnière","Quartiles par saison"),
                                dcc.Graph(figure=season_fig, config=dict(displayModeBar=False))]),
                ]),
            ]),
            dcc.Tab(label="↕  Comparaison 3 zones",  className="custom-tab", selected_className="custom-tab--selected", children=[...]),
            dcc.Tab(label="≋  Anomalies & tendances", className="custom-tab", selected_className="custom-tab--selected", children=[...]),
            dcc.Tab(label="◎  Carte animée",          className="custom-tab", selected_className="custom-tab--selected", children=[...]),
        ]
    ),
])

if __name__ == "__main__":
    app.run(debug=True)
"""
